/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HM50FzhfJ3f
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export function Article() {
  return (
    <main className="flex flex-row gap-6">
      <section className="w-2/3">
        <Card>
          <CardHeader>
            <CardTitle>Forståelse av Kardiologi: En Omfattende Guide</CardTitle>
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <span>Dr. John Doe</span>
              <Badge>Kardiolog</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="mb-4 text-sm text-gray-500">Publisert den: 1. januar, 2024</div>
            <p className="mb-4">
              Kardiologi er en gren av medisinen som tar for seg lidelser i hjertet, samt deler av det sirkulatoriske
              systemet. Dette feltet inkluderer diagnose og behandling av medfødte hjertefeil, koronar arteriesykdom,
              hjertesvikt, og mer.
            </p>
            <p>Hjertet, et vitalt organ i kroppen, har fire hovedfunksjoner...</p>
          </CardContent>
          <CardFooter className="flex flex-col space-y-2">
            <h4 className="font-semibold">Referanser:</h4>
            <ul className="list-disc list-inside">
              <li>
                <Link href="#">Hjertehelse: En Omfattende Oversikt</Link>
              </li>
              <li>
                <Link href="#">Kardiologi: Fra Grunnleggende til Avansert</Link>
              </li>
            </ul>
          </CardFooter>
        </Card>
      </section>
      <aside className="w-1/3">
        <Card>
          <CardHeader>
            <CardTitle>Relatert Informasjon</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <h4 className="font-semibold">Relaterte Artikler</h4>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  <Link href="#">Grunnleggende om Kardiovaskulært System</Link>
                </li>
                <li>
                  <Link href="#">Forståelse av Hjertesykdom</Link>
                </li>
              </ul>
              <h4 className="font-semibold">Medisinsk Ordbok</h4>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  <Link href="#">Kardiovaskulær Terminologi</Link>
                </li>
                <li>
                  <Link href="#">Ordbok over Hjertesykdomsbetingelser</Link>
                </li>
              </ul>
              <h4 className="font-semibold">Hjelpsomme Ressurser</h4>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  <Link href="#">Amerikansk Hjerteassosiasjon</Link>
                </li>
                <li>
                  <Link href="#">Verdens Helseorganisasjon</Link>
                </li>
              </ul>
            </div>
          </CardContent>
        </Card>
      </aside>
    </main>
  )
}
