/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kqw75g1HA6s
 */
import { Button } from "@/components/ui/button"

export function Knapp() {
  return (
    <Button className="transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-110">
      Click Me
      <ArrowRightIcon className="ml-2 w-4 h-4" />
    </Button>
  )
}


function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}
